# Generated by Django 4.2.5 on 2023-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=20)),
                ('num_books', models.IntegerField()),
            ],
        ),
    ]
